Fix TypeError when CMAKE_GENERATOR isn't present (#128)
While building, I received this error at the line corrected:
TypeError: argument of type 'NoneType' is not iterable

This happens because get_variable_from_cmake_cache() returns None. This line fixes it.